Html dev
galeoconsulting/galeo-site-dev pull request #3
Opened 2017-02-27 19:56 UTC by JAlbertins

Iekšlapa

2017-03-01 19:09 UTC, reinisz commented
svg definīcijas ir, bet iekodēti ir png.

2017-03-02 10:03 UTC, JAlbertins commented
Labots.

2017-03-07 08:32 UTC, JanisPlots requested changes
Remove unused .js files

2017-03-07 08:32 UTC, JanisPlots commented on js/custom.js
> +    $('.sky-part:not(.sky-part-v2)').css({minHeight: $(window).height()});
Can be done with CSS3 '100vh', but anyway can't find selector for element.
Should't this be modified for resize event below as well?

2017-03-07 08:32 UTC, JanisPlots commented on inpage.html
> +          <svg class="svg-img" xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 64 64"><defs><style>.\34 b5e0f8b-7237-4c8b-b762-0790343f8d20,.\35 ba875d0-6564-424d-a79d-a5344763
Remove commented code.

2017-03-07 08:32 UTC, JanisPlots commented on css/styles.scss
> +          "partials/structure",
Minor code formatting issue

2017-03-07 08:32 UTC, JanisPlots commented on css/styles.scss
>  @import "bootstrap/bootstrap",
Import only used bootstrap components.

2017-03-07 08:32 UTC, JanisPlots commented on js/custom.js
>      $(window).scroll(function(){
Remove debug code: console.log(bgOff);

2017-03-07 08:32 UTC, JanisPlots commented on inpage.html
> +          <svg class="svg-img" xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 64 64"><defs><style>.\34 b5e0f8b-7237-4c8b-b762-0790343f8d20,.\35 ba875d0-6564-424d-a79d-a5344763
Cleanup.

2017-03-07 08:32 UTC, JanisPlots commented on inpage.html
> +          <svg class="svg-img" xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 64 64"><defs><style>.\34 b5e0f8b-7237-4c8b-b762-0790343f8d20,.\35 ba875d0-6564-424d-a79d-a5344763
Cleanup. var contentString = "Some content";

2017-03-07 08:32 UTC, JanisPlots commented on inpage.html
> +          <svg class="svg-img" xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 64 64"><defs><style>.\34 b5e0f8b-7237-4c8b-b762-0790343f8d20,.\35 ba875d0-6564-424d-a79d-a5344763
Remove commented code.

2017-03-08 08:59 UTC, JAlbertins commented on js/custom.js
> +    $('.sky-part:not(.sky-part-v2)').css({minHeight: $(window).height()});
More than 20% users could not see this, if using vh.

2017-03-10 07:19 UTC, JAlbertins reviewed
Viss šķiet ok. Boostrap atsevišķas komponentes - izskatīšu. Man nav tiesību apstiprināt Merge.

2017-03-10 07:34 UTC, JAlbertins reviewed
Bootstrap components for Nav and grid.

2017-03-13 14:19 UTC, JanisPlots commented on js/custom.js
> +    $('.sky-part:not(.sky-part-v2)').css({minHeight: $(window).height()});
Please read the whole comment

2017-03-13 14:20 UTC, JanisPlots commented on js/custom.js
>      $(window).scroll(function(){
Has not been done

2017-03-13 14:21 UTC, JanisPlots commented on inpage.html
> +          <svg class="svg-img" xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 64 64"><defs><style>.\34 b5e0f8b-7237-4c8b-b762-0790343f8d20,.\35 ba875d0-6564-424d-a79d-a5344763
Has not been done. Please see 'File changes' of pull request this view didn't put the comment on right line.

2017-03-13 14:21 UTC, JanisPlots commented on inpage.html
> +          <svg class="svg-img" xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 64 64"><defs><style>.\34 b5e0f8b-7237-4c8b-b762-0790343f8d20,.\35 ba875d0-6564-424d-a79d-a5344763
Has not been done. Please see 'File changes' of pull request this view didn't put the comment on right line.

2017-03-13 14:21 UTC, JanisPlots commented on inpage.html
> +          <svg class="svg-img" xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 64 64"><defs><style>.\34 b5e0f8b-7237-4c8b-b762-0790343f8d20,.\35 ba875d0-6564-424d-a79d-a5344763
Has not been done. Please see 'File changes' of pull request this view didn't put the comment on right line.

2017-03-16 12:00 UTC, gatisj commented
Es saprotu ka tur vēl paliek kaut kādi sīkumi ko vēlāk jālabo, bet tagad merojam iekšā lai turpinātu procesu.

2017-03-16 12:00 UTC, merged